=== newborne/zhfw-all/6 Weather Web Service/ZHFW-Weather/src/main/resources/WeatherDB.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/WeatherDB" xmlns:tns="http://www.example.org/WeatherDB" elementFormDefault="qualified">

    <element name="weathers" type="tns:WeatherList"></element>

    <complexType name="WeatherInfo">
    	<sequence>
    		<element name="date" type="tns:DateInfo" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="location" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="description" type="tns:WeatherType"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="temperature" type="double" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="DateInfo">
    	<sequence>
    		<element name="year" type="int"></element>
    		<element name="month" type="int"></element>
    		<element name="date" type="int"></element>
    	</sequence>
    </complexType>

    <simpleType name="WeatherType">
    	<restriction base="string">
    		<enumeration value="sunny"></enumeration>
    		<enumeration value="cloudy"></enumeration>
    		<enumeration value="rainy"></enumeration>
    		<enumeration value="snow"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="WeatherList">
    	<sequence>
    		<element name="weather" type="tns:WeatherInfo"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>
</schema>

=== newborne/zhfw-all/5 Flight Ticket Service/ZHFW-FlightTicket/datasource/ds_2_6.xml
<?xml version="1.0" encoding="UTF-8"?>
<weat:weathers xmlns:weat="http://www.example.org/WeatherDB" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/WeatherDB ../ZHFW-Weather/src/main/resources/WeatherDB.xsd">
  <!--1 or more repetitions:-->
  <weat:weather>
    <weat:date>
      <weat:year>2012</weat:year>
      <weat:month>11</weat:month>
      <weat:date>15</weat:date>
    </weat:date>
    <weat:location>Vienna</weat:location>
    <weat:description>rainy</weat:description>
    <weat:temperature>12.3</weat:temperature>
  </weat:weather>
  <weat:weather>
    <weat:date>
      <weat:year>2012</weat:year>
      <weat:month>11</weat:month>
      <weat:date>15</weat:date>
    </weat:date>
    <weat:location>Munich</weat:location>
    <weat:description>rainy</weat:description>
    <weat:temperature>10.3</weat:temperature>
  </weat:weather>
</weat:weathers>
